import javax.swing.*;
import java.awt.*;

public class MainForm {
    private JPanel mainPanel;
    private JButton yesButton;
    private JButton noButton;
    private JLabel question;
    private JLabel задумайтеЧислоОт1Label;

    private GameState state = GameState.NEW_GAME;
    private int min, max; // Границы наших догадок
    private int guess = -1; // Текущая наша догадка

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    private MainForm() {
        yesButton.addActionListener(e -> {
            switch (state) {
                case GAME_OVER:
                case NEW_GAME:
                    min = 1;
                    max = 100;
                    state = GameState.STARTED;
                    nextQuestion();
                    break;
                case STARTED:
                    min = guess + 1;
                    nextQuestion();
                    break;
            }
        });
        noButton.addActionListener(e -> {
            switch (state) {
                case NEW_GAME:
                    question.setText("Я буду ждать :) Задумали ли число?");
                    break;
                case STARTED:
                    max = guess;
                    nextQuestion();
                    break;
                case GAME_OVER:
                    System.exit(0);
                    break;
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("Игра Угадай число");
        frame.setContentPane(new MainForm().mainPanel);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    private void nextQuestion() {
        if (min == max) {
            question.setText("Ваше число " + min + ". Ещё раз?");
            state = GameState.GAME_OVER;
            return;
        }
        guess = (min + max) / 2;
        question.setText("Число больше " + guess + "?");
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        задумайтеЧислоОт1Label = new JLabel();
        задумайтеЧислоОт1Label.setFont(new Font(задумайтеЧислоОт1Label.getFont().getName(), задумайтеЧислоОт1Label.getFont().getStyle(), 18));
        задумайтеЧислоОт1Label.setText("Задумайте число от 1 до 100 и я его угадаю задавая вопросы с ответом ДА и НЕТ");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        mainPanel.add(задумайтеЧислоОт1Label, gbc);
        yesButton = new JButton();
        yesButton.setEnabled(true);
        yesButton.setFont(new Font(yesButton.getFont().getName(), yesButton.getFont().getStyle(), 24));
        yesButton.setText("ДА");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 1;
        gbc.ipady = 1;
        gbc.insets = new Insets(2, 2, 2, 2);
        mainPanel.add(yesButton, gbc);
        noButton = new JButton();
        noButton.setEnabled(true);
        noButton.setFont(new Font(noButton.getFont().getName(), noButton.getFont().getStyle(), 24));
        noButton.setText("НЕТ");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(2, 2, 2, 2);
        mainPanel.add(noButton, gbc);
        question = new JLabel();
        question.setFont(new Font(question.getFont().getName(), question.getFont().getStyle(), 36));
        question.setText("Вы задумали число?");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        mainPanel.add(question, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
